FROM postgres:latest

# Environment variables
ENV POSTGRES_DB=${POSTGRES_DB}
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Copy SQL script to initialize the database
COPY ./scripts/init.sql /docker-entrypoint-initdb.d/
EXPOSE 5432

